### ISSUE TITLE
can not run example1 TCGA-ZG-A8QZ-01

### ISSUE THREAD

**Issue by rebeccasun** [ChrisMaherLab/INTEGRATE-Vis#6]
Hi 
I tried to run the example command as below, I followed the instructions and downloaded GRCh38_r85.all.fa, Homo_sapiens.GRCh38.85.gtf  and Ideogram.38.tsv. However, I got some error messages. 

`Integrate-vis.py structure -b ~/Downloads/INTEGRATE-Vis-master/example/Example1/TCGA_PRAD_333_bedpe/TCGA-ZG-A8QZ-01.bedpe -s TCGA-ZG-A8QZ-01 -r GRCh38_r85.all.fa -d Ideogram.38.tsv -g Homo_sapiens.GRCh38.85.gtf -m ~/Downloads/INTEGRATE-Vis-master/example/Example1/simulated.TCGA-ZG-A8QZ-01.bam `

---------------------ERROR-------------------------
```
Command: python ~/opt/bin/pa.py -5 ENSG00000164815 -3 ENSG00000179912 -f 104197724 -t 57395818 -p "VLDKAEYLRDMEANLLPGFLRLQELRLDLFLICDAIPALDSWRLSIYS 25 0 ENST00000297431(1374)|ENST00000447452(915);;ENST00000347140|ENST00000402412|ENST00000634871" -b ~/Downloads/INTEGRATE-Vis-master/example/Example1/simulated.TCGA-ZG-A8QZ-01.bam -d ~/vis/Ideogram.38.tsv -m ~/vis/Homo_sapiens.GRCh38.85.gtf -o ~/vis/TCGA-ZG-A8QZ-01.ORC5--R3HDM2.7-104197725.12-57395818.structure.pdf
Traceback (most recent call last):
  File "~/opt/bin/pa.py", line 885, in <module>
    sys.exit(main(sys.argv))
  File "~/opt/bin/pa.py", line 881, in main
    panel = PANEL_A(argv)
  File "~/opt/bin/pa.py", line 208, in __init__
    self.set_scales(self.ch_5, self.ch_3 ,self.ideogram_dir)
  File "~/opt/bin/pa.py", line 458, in set_scales
    ch_length_5 = int(ch_regions_5[-1][2])
IndexError: list index out of range
```
Could you please take a look at this?

Thanks,

**Comment by ljmills** [comment]
I am having the same issue.
